title: Book of SHUI
email: imbahui@163.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a website describing the theories, methods, and implementation of
  the Simulator of catchment Hydrology and nUtrients Interactions (SHUI).

github_username:  hxie2023

# Build settings
# theme: minima
remote_theme: "just-the-docs/just-the-docs"

# 添加这行配置
sass:
  style: compressed
  load_paths:
    - _sass

kramdown:
  math_engine: mathjax 
  syntax_highlighter: rouge
  input: GFM
  math_engine_opts:
    enable_dollar_delimiter: true

# Just the Docs 主题配置
just_the_docs:
  # ============================================
  # 关键：添加 MathJax 脚本
  # ============================================
  head_scripts:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - /assets/css/custom.css  # 保持您的原有自定义 CSS 引用

plugins:
  - jekyll-feed
  - jekyll-remote-theme 
  - jekyll-default-layout # Just the Docs 


baseurl: "/SHUI"
url: "https://hxie2023.github.io"

# ---------------------------------------------
# 关键：添加 _pages 文件夹到处理列表
# ---------------------------------------------
include: 
  - _pages


