# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Book of SHUI
email: imbahui@163.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a website describing the theories, methods, and implementation of
  the Simulator of catchment Hydrology and nUtrients Interactions (SHUI).

github_username:  hxie2023

# Build settings
# theme: minima
remote_theme: "just-the-docs/just-the-docs"

# 添加这行配置
sass:
  style: compressed
  load_paths:
    - _sass

kramdown:
  math_engine: nil 

# Just the Docs 主题配置
just_the_docs:
  # ============================================
  # 关键：添加 MathJax 脚本
  # ============================================
  head_scripts:
    - /assets/css/custom.css  # 保持您的原有自定义 CSS 引用
    
    # 1. KaTeX CSS 文件
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css" crossorigin="anonymous">
    
    # 2. KaTeX JS 核心库
    - <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js" crossorigin="anonymous"></script>
    
    # 3. KaTeX 自动渲染扩展 (Auto-render extension)
    #    在加载完成后，自动查找页面中的公式并渲染。
    #    配置了分隔符: '$$...$$' (块级) 和 '$...$' (行内)
    - <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js" crossorigin="anonymous" onload="renderMathInElement(document.body, { delimiters: [ {left: '$$', right: '$$', display: true}, {left: '$', right: '$', display: false} ]});"></script>



plugins:
  - jekyll-feed
  - jekyll-remote-theme 
  - jekyll-default-layout # Just the Docs 


baseurl: "/SHUI"
url: "https://hxie2023.github.io"

# ---------------------------------------------
# 关键：添加 _pages 文件夹到处理列表
# ---------------------------------------------
include: 
  - _pages


